/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const AccessoryPrices = IDL.Record({
  'pipeCleanerBag' : IDL.Nat,
  'pipeCleanerFramework' : IDL.Nat,
  'scrunchies' : IDL.Nat,
  'earrings' : IDL.Nat,
  'keychain' : IDL.Nat,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'customizationDetails' : IDL.Text,
  'productName' : IDL.Text,
  'preferredDeliveryDate' : IDL.Text,
  'quantity' : IDL.Nat,
  'phoneNumber' : IDL.Text,
  'instagramId' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'instagramHandle' : IDL.Text,
  'emailAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Text, CartItem], [], []),
  'clearCart' : IDL.Func([IDL.Text], [], []),
  'getAccessoryPrices' : IDL.Func([], [AccessoryPrices], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'removeItemFromCart' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitOrder' : IDL.Func([Order], [], []),
  'updateAccessoryPrices' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateContactInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const AccessoryPrices = IDL.Record({
    'pipeCleanerBag' : IDL.Nat,
    'pipeCleanerFramework' : IDL.Nat,
    'scrunchies' : IDL.Nat,
    'earrings' : IDL.Nat,
    'keychain' : IDL.Nat,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'customizationDetails' : IDL.Text,
    'productName' : IDL.Text,
    'preferredDeliveryDate' : IDL.Text,
    'quantity' : IDL.Nat,
    'phoneNumber' : IDL.Text,
    'instagramId' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'instagramHandle' : IDL.Text,
    'emailAddress' : IDL.Text,
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Text, CartItem], [], []),
    'clearCart' : IDL.Func([IDL.Text], [], []),
    'getAccessoryPrices' : IDL.Func([], [AccessoryPrices], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'removeItemFromCart' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitOrder' : IDL.Func([Order], [], []),
    'updateAccessoryPrices' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateContactInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };