/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessoryPrices {
  'pipeCleanerBag' : bigint,
  'pipeCleanerFramework' : bigint,
  'scrunchies' : bigint,
  'earrings' : bigint,
  'keychain' : bigint,
}
export interface CartItem {
  'productId' : string,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface ContactInfo {
  'instagramHandle' : string,
  'emailAddress' : string,
}
export interface Order {
  'customerName' : string,
  'deliveryAddress' : string,
  'customizationDetails' : string,
  'productName' : string,
  'preferredDeliveryDate' : string,
  'quantity' : bigint,
  'phoneNumber' : string,
  'instagramId' : string,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<[string, CartItem], undefined>,
  'clearCart' : ActorMethod<[string], undefined>,
  'getAccessoryPrices' : ActorMethod<[], AccessoryPrices>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCart' : ActorMethod<[string], Array<CartItem>>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'removeItemFromCart' : ActorMethod<[string, string], undefined>,
  'submitOrder' : ActorMethod<[Order], undefined>,
  'updateAccessoryPrices' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updateContactInfo' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];